<Window
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:Autocad_WFP_ADD_Cirsle_21_03_2023"
             xmlns:DatabaseServices="clr-namespace:Autodesk.AutoCAD.DatabaseServices;assembly=Acdbmgd" x:Name="WF1" x:Class="Autocad_WFP_ADD_Cirsle_21_03_2023.WPF_Form"
             mc:Ignorable="d" 
             d:DesignHeight="250" d:DesignWidth="400" WindowStartupLocation="CenterOwner" MinHeight="200" MinWidth="400" SizeToContent="WidthAndHeight">
    <Grid x:Name="GR1">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="80*"/>
        </Grid.RowDefinitions>
        <Button x:Name="B0" Margin="5" Content="Button" Grid.Row="9" Grid.Column="0"/>
        <Button x:Name="B1" Margin="5" Content="Button" Grid.Row="9" Grid.Column="1"/>
        <Button x:Name="B2" Margin="5" Content="Button" Grid.Row="9" Grid.Column="2"/>
        <Button x:Name="B3" Margin="5" Content="Button" Grid.Row="9" Grid.Column="3"/>
        <Button x:Name="B4" Margin="5" Content="Button" Grid.Row="9" Grid.Column="4"/>
        <Button x:Name="B5" Margin="5" Content="Button" Grid.Row="9" Grid.Column="5"/>
        <Button x:Name="B6" Margin="5" Content="Button" Grid.Row="9" Grid.Column="6"/>
        <Button x:Name="B7" Margin="5" Content="Button" Grid.Row="9" Grid.Column="7"/>
        <Button x:Name="B8" Margin="5" Content="Add_Circle" Grid.Row="9" Grid.Column="8" Click="B8_Click"/>
        <TextBox Name="TextBox1" Margin="10" Grid.Row="0" Grid.Column="0" Grid.RowSpan="8"
                 Grid.ColumnSpan="4" TextWrapping="Wrap" VerticalScrollBarVisibility="Auto"
                 AcceptsReturn="True" TextChanged="TextBox1_TextChanged"  />
        <TextBox Name="TextBox2" Margin="10" Grid.Row="0" Grid.Column="4" Grid.RowSpan="8"
                 Grid.ColumnSpan="4" TextWrapping="Wrap" VerticalScrollBarVisibility="Auto"
                 AcceptsReturn="True"  />

    </Grid>
</Window>
